In [4]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

2.4.1


# Multi-variable linear regression
Predicting exam score - regression using three inputs (x1, x2, x3)

x1 (quiz 1) | x2 (quiz 2) | x3 (mid 1) | Y (final)
---- | ---- | ----| ----
73 | 80 | 75 | 152
93 | 88 | 93 | 185
89 | 91 | 90 | 180
96 | 98 | 100 | 196
73 | 66 | 70 | 142


Test Scores for General Psychology ( https://goo.gl/g2T8Kp )

# Matrix multiplication

## dot product(=scalar product, 내적)
<img src="https://www.mathsisfun.com/algebra/images/matrix-multiply-a.svg" >


https://www.mathsisfun.com/algebra/matrix-multiplying.html

# Multi-feature regression

### Hypothesis

$$ H(x) = w x + b $$

$$ H(x_1, x_2, x_3) = w_1 x_1 + w_2 x_2 + w_3 x_3 + b $$  
각 변수에 대한 w 값이 필요함

# Hypothesis using matrix

$$ H(x_1, x_2, x_3) = \underline{w_1 x_1 + w_2 x_2 + w_3 x_3} + b $$

$$ w_1 x_1 + w_2 x_2 + w_3 x_3 $$ 

$$ \begin{pmatrix} w_{ 1 } & w_{ 2 } & w_{ 3 } \end{pmatrix}\cdot \begin{pmatrix} x_{ 1 } \\ x_{ 2 } \\ x_{ 3 } \end{pmatrix} $$

$$ WX $$ (W, X 는 matrix)

# Hypothesis without b

$$ H(x_1, x_2, x_3) = w_1 x_1 + w_2 x_2 + w_3 x_3 + b$$

$$ = b + w_1 x_1 + w_2 x_2 + w_3 x_3 $$

$$ = \begin{pmatrix} b & x_{ 1 } & x_{ 2 } & x_{ 3 } \end{pmatrix}\cdot \begin{pmatrix} 1 \\ w_{ 1 } \\ w_{ 2 } \\ w_{ 3 } \end{pmatrix} $$

$$ = XW $$



# Hypothesis using matrix 

### Many x instances

$$ \begin{pmatrix} x_{ 11 } & x_{ 12 } & x_{ 13 } \\ x_{ 21 } & x_{ 22 } & x_{ 23 } \\ x_{ 31 } & x_{ 32 } & x_{ 33 }\\ x_{ 41 } & x_{ 42 } & x_{ 43 }\\ x_{ 51 } & x_{ 52 } & x_{ 53 }\end{pmatrix} \cdot \begin{pmatrix} w_{ 1 } \\ w_{ 2 } \\ w_{ 3 } \end{pmatrix}=\begin{pmatrix} x_{ 11 }w_{ 1 }+x_{ 12 }w_{ 2 }+x_{ 13 }w_{ 3 } \\ x_{ 21 }w_{ 1 }+x_{ 22 }w_{ 2 }+x_{ 23 }w_{ 3 }\\ x_{ 31 }w_{ 1 }+x_{ 32 }w_{ 2 }+x_{ 33 }w_{ 3 } \\ x_{ 41 }w_{ 1 }+x_{ 42 }w_{ 2 }+x_{ 43 }w_{ 3 } \\ x_{ 51 }w_{ 1 }+x_{ 52 }w_{ 2 }+x_{ 53 }w_{ 3 } \end{pmatrix} $$

$$ [5, 3] \cdot [3, 1] = [5, 1] $$

$$ H(X) = XW $$

5는 데이터(instance)의 수, 3은 변수(feature)의 수, 1은 결과

# Hypothesis using matrix (n output)

$$ [n, 3] \cdot [?, ?] = [n, 2] $$

$$ H(X) = XW $$

* n은 데이터(instance)의 개수, 2는 결과 값의 개수로 주어진다.
* 이때, W [?, ?] ⇒ [3, 2]

# WX vs XW

### Theory (Lecture) :
 $$ H(x) = Wx + b  $$

### TensorFlow (Implementation) :

$$ H(X) = XW $$

# Simple Example (2 variables)

x1 | x2 | y
---- | ---- | ----
1  |  0  |  1
0  |  2  |  2
3  |  0  |  3
0  |  4  |  4
5  |  0  |  5

In [18]:
tf.random.set_seed(0)  # for reproducibility

In [40]:
x1_data = [1, 0, 3, 0, 5]
x2_data = [0, 2, 0, 4, 0]
y_data  = [1, 2, 3, 4, 5]

W1 = tf.Variable(tf.random.uniform((1,), -10.0, 10.0))
W2 = tf.Variable(tf.random.uniform((1,), -10.0, 10.0))
b  = tf.Variable(tf.random.uniform((1,), -10.0, 10.0))

learning_rate = tf.Variable(0.001)

print("{:5s} | {:>10.6s} | {:>10.4s} | {:>10.4s} | {:>10.6s}".format( "epoch","cost","W1","W2","b"))
for i in range(1000+1):
    with tf.GradientTape() as tape:
        hypothesis = W1 * x1_data + W2 * x2_data + b
        cost = tf.reduce_mean(tf.square(hypothesis - y_data))
        
    W1_grad, W2_grad, b_grad = tape.gradient(cost, [W1, W2, b])
    W1.assign_sub(learning_rate * W1_grad)
    W2.assign_sub(learning_rate * W2_grad)
    b.assign_sub(learning_rate * b_grad)

    if i % 50 == 0:
        print("{:5} | {:10.6f} | {:10.4f} | {:10.4f} | {:10.6f}".format(
          i, cost.numpy(), W1.numpy()[0], W2.numpy()[0], b.numpy()[0]))


epoch |       cost |         W1 |         W2 |          b
    0 | 156.990295 |     6.9780 |     4.2124 |  -5.968578
   50 |  41.852776 |     4.7775 |     3.7767 |  -6.553596
  100 |  16.238819 |     3.7377 |     3.5222 |  -6.778894
  150 |  10.350182 |     3.2397 |     3.3644 |  -6.833573
  200 |   8.829857 |     2.9943 |     3.2595 |  -6.807239
  250 |   8.288828 |     2.8666 |     3.1845 |  -6.742532
  300 |   7.974858 |     2.7937 |     3.1268 |  -6.659857
  350 |   7.719106 |     2.7462 |     3.0795 |  -6.569052
  400 |   7.482807 |     2.7107 |     3.0386 |  -6.474894
  450 |   7.256645 |     2.6808 |     3.0019 |  -6.379736
  500 |   7.038133 |     2.6536 |     2.9679 |  -6.284741
  550 |   6.826455 |     2.6279 |     2.9357 |  -6.190496
  600 |   6.621229 |     2.6030 |     2.9049 |  -6.097299
  650 |   6.422207 |     2.5787 |     2.8750 |  -6.005295
  700 |   6.229178 |     2.5548 |     2.8460 |  -5.914558
  750 |   6.041956 |     2.5312 |     2.8177 |  -5.825120
  800 |   5.86

# Simple Example (2 variables with Matrix)

In [39]:
x_data = [
    [1., 0., 3., 0., 5.], # x1
    [0., 2., 0., 4., 0.]  # x2
]
y_data  = [1, 2, 3, 4, 5]

W = tf.Variable(tf.random.uniform((1, 2), -1.0, 1.0))
b = tf.Variable(tf.random.uniform((1,), -1.0, 1.0))

learning_rate = tf.Variable(0.001)

print("{:5s} | {:>10.6s} | {:>10.4s} | {:>10.4s} | {:>10.6s}".format( "epoch","cost","W1","W2","b"))
for i in range(1000+1):
    with tf.GradientTape() as tape:
        hypothesis = tf.matmul(W, x_data) + b # (1, 2) * (2, 5) = (1, 5)
        cost = tf.reduce_mean(tf.square(hypothesis - y_data))

        W_grad, b_grad = tape.gradient(cost, [W, b])
        W.assign_sub(learning_rate * W_grad)
        b.assign_sub(learning_rate * b_grad)
    
    if i % 50 == 0:
        print("{:5} | {:10.6f} | {:10.4f} | {:10.4f} | {:10.6f}".format(
            i, cost.numpy(), W.numpy()[0][0], W.numpy()[0][1], b.numpy()[0]))

epoch |       cost |         W1 |         W2 |          b
    0 |   1.638827 |     0.3503 |     0.6276 |   0.781139
   50 |   0.473447 |     0.5729 |     0.6699 |   0.836680
  100 |   0.213363 |     0.6784 |     0.6949 |   0.856284
  150 |   0.152576 |     0.7294 |     0.7106 |   0.858900
  200 |   0.135874 |     0.7549 |     0.7213 |   0.853497
  250 |   0.129053 |     0.7685 |     0.7293 |   0.844330
  300 |   0.124540 |     0.7765 |     0.7356 |   0.833432
  350 |   0.120644 |     0.7820 |     0.7409 |   0.821779
  400 |   0.116978 |     0.7862 |     0.7457 |   0.809842
  450 |   0.113451 |     0.7899 |     0.7501 |   0.797852
  500 |   0.110038 |     0.7932 |     0.7542 |   0.785920
  550 |   0.106729 |     0.7964 |     0.7581 |   0.774104
  600 |   0.103521 |     0.7996 |     0.7619 |   0.762433
  650 |   0.100410 |     0.8026 |     0.7656 |   0.750917
  700 |   0.097392 |     0.8056 |     0.7692 |   0.739564
  750 |   0.094465 |     0.8085 |     0.7727 |   0.728376
  800 |   0.09

# Hypothesis without b
- 해당 코드의 tf.keras.optimizers.SGD 같은 경우 추후 설명
- matrix, gradient에 치중해서 코드를 보기 바랍니다.

In [35]:
import tensorflow as tf

# 앞의 코드에서 bias(b)를 행렬에 추가
x_data = [
    [1., 1., 1., 1., 1.], # bias(b)
    [1., 0., 3., 0., 5.], 
    [0., 2., 0., 4., 0.]
]
y_data  = [1, 2, 3, 4, 5]

W = tf.Variable(tf.random.uniform((1, 3), -1.0, 1.0)) # [1, 3]으로 변경하고, b 삭제

learning_rate = 0.001
optimizer = tf.keras.optimizers.SGD(learning_rate)

print("{:5s} | {:>10.6s} | {:>10.4s} | {:>10.4s} | {:>10.6s}".format( "epoch","cost","W1","W2","W3"))
for i in range(1000+1):
    with tf.GradientTape() as tape:
        hypothesis = tf.matmul(W, x_data) # b가 없다
        cost = tf.reduce_mean(tf.square(hypothesis - y_data))

    grads = tape.gradient(cost, [W])
    optimizer.apply_gradients(grads_and_vars=zip(grads,[W]))
    if i % 50 == 0:
        print("{:5} | {:10.6f} | {:10.4f} | {:10.4f} | {:10.4f}".format(
            i, cost.numpy(), W.numpy()[0][0], W.numpy()[0][1], W.numpy()[0][2]))

    0 |   7.240298 |     0.0610 |     0.3030 |     0.0054
   50 |   2.202286 |     0.2372 |     0.6339 |     0.3182
  100 |   0.757683 |     0.3289 |     0.7811 |     0.5150
  150 |   0.297664 |     0.3767 |     0.8453 |     0.6400
  200 |   0.136139 |     0.4009 |     0.8726 |     0.7203
  250 |   0.074774 |     0.4122 |     0.8840 |     0.7724
  300 |   0.049964 |     0.4163 |     0.8887 |     0.8065
  350 |   0.039313 |     0.4163 |     0.8908 |     0.8292
  400 |   0.034360 |     0.4138 |     0.8921 |     0.8445
  450 |   0.031759 |     0.4100 |     0.8931 |     0.8550
  500 |   0.030149 |     0.4053 |     0.8942 |     0.8625
  550 |   0.028968 |     0.4001 |     0.8954 |     0.8681
  600 |   0.027982 |     0.3947 |     0.8966 |     0.8723
  650 |   0.027093 |     0.3891 |     0.8980 |     0.8757
  700 |   0.026258 |     0.3834 |     0.8994 |     0.8785
  750 |   0.025461 |     0.3778 |     0.9008 |     0.8809
  800 |   0.024692 |     0.3722 |     0.9022 |     0.8831
  850 |   0.02

# Custom Gradient
* tf.train.GradientDescentOptimizer(): optimizer
* optimizer.apply_gradients(): update

- 해당 코드도 우선 참고 사항으로 알아두기 바랍니다.

In [36]:
# Multi-variable linear regression (1)

X = tf.constant([[1., 2.], 
                 [3., 4.]])
y = tf.constant([[1.5], [3.5]])

W = tf.Variable(tf.random.normal((2, 1)))
b = tf.Variable(tf.random.normal((1,)))

# Create an optimizer
optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)

n_epoch = 1000+1
print("epoch | cost")
for i in range(n_epoch):
    # Use tf.GradientTape() to record the gradient of the cost function
    with tf.GradientTape() as tape:
        y_pred = tf.matmul(X, W) + b
        cost = tf.reduce_mean(tf.square(y_pred - y))

    # calculates the gradients of the loss
    grads = tape.gradient(cost, [W, b])
    
    # updates parameters (W and b)
    optimizer.apply_gradients(grads_and_vars=zip(grads, [W, b]))
    if i % 50 == 0:
        print("{:5} | {:10.6f}".format(i, cost.numpy()))


epoch | cost
    0 | 101.103889
   50 |   0.003188
  100 |   0.002180
  150 |   0.001490
  200 |   0.001019
  250 |   0.000697
  300 |   0.000476
  350 |   0.000326
  400 |   0.000223
  450 |   0.000152
  500 |   0.000104
  550 |   0.000071
  600 |   0.000049
  650 |   0.000033
  700 |   0.000023
  750 |   0.000016
  800 |   0.000011
  850 |   0.000007
  900 |   0.000005
  950 |   0.000003
 1000 |   0.000002


# 아래 코드부터가 모두의 딥러닝 강의 부분에 포함됐던것

# Predicting exam score
regression using three inputs (x1, x2, x3)

x1 (quiz 1) | x2 (quiz 2) | x3 (mid 1) | Y (final)
---- | ---- | ----| ----
73 | 80 | 75 | 152
93 | 88 | 93 | 185
89 | 91 | 90 | 180
96 | 98 | 100 | 196
73 | 66 | 70 | 142

In [ ]:
tf.random.set_seed(0)  # for reproducibility


```python

# data and label
x1 = [ 73.,  93.,  89.,  96.,  73.]
x2 = [ 80.,  88.,  91.,  98.,  66.]
x3 = [ 75.,  93.,  90., 100.,  70.]
Y  = [152., 185., 180., 196., 142.] # label, true value

# weights
w1 = tf.Variable(10.)
w2 = tf.Variable(10.)
w3 = tf.Variable(10.)
b  = tf.Variable(10.)

hypothesis = w1 * x1 +  w2 * x2 + w3 * x3 + b        
```

In [38]:
# data and label
x1 = [ 73.,  93.,  89.,  96.,  73.]
x2 = [ 80.,  88.,  91.,  98.,  66.]
x3 = [ 75.,  93.,  90., 100.,  70.]
Y  = [152., 185., 180., 196., 142.]

# weights
w1 = tf.Variable(10.)
w2 = tf.Variable(10.)
w3 = tf.Variable(10.)
b  = tf.Variable(10.)

learning_rate = 0.000001

for i in range(1000+1):
    # tf.GradientTape() to record the gradient of the cost function
    with tf.GradientTape() as tape:
        hypothesis = w1 * x1 +  w2 * x2 + w3 * x3 + b
        cost = tf.reduce_mean(tf.square(hypothesis - Y))
    # calculates the gradients of the cost
    w1_grad, w2_grad, w3_grad, b_grad = tape.gradient(cost, [w1, w2, w3, b])
    
    # update w1,w2,w3 and b
    w1.assign_sub(learning_rate * w1_grad)
    w2.assign_sub(learning_rate * w2_grad)
    w3.assign_sub(learning_rate * w3_grad)
    b.assign_sub(learning_rate * b_grad)

    if i % 50 == 0:
        print("{:5} | {:12.4f}".format(i, cost.numpy()))

    0 | 5793889.5000
   50 |   64291.1562
  100 |     715.2903
  150 |       9.8461
  200 |       2.0152
  250 |       1.9252
  300 |       1.9210
  350 |       1.9177
  400 |       1.9145
  450 |       1.9114
  500 |       1.9081
  550 |       1.9050
  600 |       1.9018
  650 |       1.8986
  700 |       1.8955
  750 |       1.8923
  800 |       1.8892
  850 |       1.8861
  900 |       1.8829
  950 |       1.8798
 1000 |       1.8767


## Multi-variable linear regression (1)
*  random  초기화: tf.random_normal()


In [17]:
# data and label
x1 = [ 73.,  93.,  89.,  96.,  73.]
x2 = [ 80.,  88.,  91.,  98.,  66.]
x3 = [ 75.,  93.,  90., 100.,  70.]
Y  = [152., 185., 180., 196., 142.] # label, true value

# weights - 초기값은 1로 줬지만 이전에도 말했다시피 이 초기값은 아무 값이나 줘도 되고 보통 랜덤값을 할당한다.
w1 = tf.Variable(tf.random.normal([1]))
w2 = tf.Variable(tf.random.normal([1]))
w3 = tf.Variable(tf.random.normal([1]))
b  = tf.Variable(tf.random.normal([1]))

# 위에서 변수가 3개이므로 weight 값도 3개가 필요하다.

learning_rate = 0.00001

print("epoch | cost")

# 학습은 Gradient descent 이용 - weight 값을 지속적으로 업데이트
for i in range(1000 + 1):
    # tf.GradientTape() to record the gradient of the cost function
    with tf.GradientTape() as tape: # with문 안에 있는 변수들에 대한 정보를 Tape에 기록
        hypothesis = w1 * x1 + w2 * x2 + w3 * x3 + b
        cost = tf.reduce_mean(tf.square(hypothesis - Y))
        
    # calculates the gradient of the cost
    # tape.gradient를 통해 cost함수에 대한 w1,w2,w3,b 변수 4개의 기울기 값을 구한다.
    w1_grad, w2_grad, w3_grad, b_grad = tape.gradient(cost, [w1,w2,w3,b]) 
    
    # update w1, w2, w3 and b
    # w1, w2, w3, b에 위에서 구한 lr * 기울기 값을 업데이트
    w1.assign_sub(learning_rate * w1_grad)
    w2.assign_sub(learning_rate * w2_grad)
    w3.assign_sub(learning_rate * w3_grad)
    b.assign_sub(learning_rate * b_grad)
    
    if i % 50 == 0:
        print("{:5} | {:12.4f}".format(i, cost.numpy()))

epoch | cost
    0 |   40574.8281
   50 |      13.1069
  100 |      12.7682
  150 |      12.4384
  200 |      12.1175
  250 |      11.8051
  300 |      11.5011
  350 |      11.2052
  400 |      10.9172
  450 |      10.6368
  500 |      10.3640
  550 |      10.0984
  600 |       9.8399
  650 |       9.5884
  700 |       9.3435
  750 |       9.1052
  800 |       8.8732
  850 |       8.6474
  900 |       8.4276
  950 |       8.2137
 1000 |       8.0055


위의 결과에서 보이듯이 cost가 매우 큰 값이였다가 일정 수준이 되면 감소하는 빈도가 줄어드는 것을 확인할 수 있다.

## Multi-variable linear regression (2)

* Matrix 사용

In [50]:
# Matrix를 이용해서 데이터 준비
data = np.array([
    # X1,   X2,    X3,   y
    [ 73.,  80.,  75., 152. ],
    [ 93.,  88.,  93., 185. ],
    [ 89.,  91.,  90., 180. ],
    [ 96.,  98., 100., 196. ],
    [ 73.,  66.,  70., 142. ]
], dtype=np.float32)

# slice data
# slice를 이용해 X, Y 값을 추출
# slice에서 ,를 기준으로 앞 부분은 행, 뒷 부분은 열을 의미한다.
X = data[:, :-1]
y = data[:, [-1]] # label, answer

W = tf.Variable(tf.random.normal((3, 1)))
b = tf.Variable(tf.random.normal((1,)))

learning_rate = 0.000001

# hypothesis, prediction function
def predict(X):
    return tf.matmul(X, W) + b

print("epoch | cost")

n_epochs = 2000
for i in range(n_epochs+1):
    # tf.GradientTape() to record the gradient of the cost function
    with tf.GradientTape() as tape:
        cost = tf.reduce_mean((tf.square(predict(X) - y)))

    # calculates the gradients of the loss
    W_grad, b_grad = tape.gradient(cost, [W, b])

    # updates parameters (W and b)
    W.assign_sub(learning_rate * W_grad)
    b.assign_sub(learning_rate * b_grad)
    
    if i % 100 == 0:
        print("{:5} | {:10.4f}".format(i, cost.numpy()))

epoch | cost
    0 |   213.9912
  100 |    15.7712
  200 |    15.6649
  300 |    15.5834
  400 |    15.5023
  500 |    15.4216
  600 |    15.3414
  700 |    15.2616
  800 |    15.1822
  900 |    15.1034
 1000 |    15.0248
 1100 |    14.9469
 1200 |    14.8693
 1300 |    14.7920
 1400 |    14.7153
 1500 |    14.6388
 1600 |    14.5628
 1700 |    14.4872
 1800 |    14.4120
 1900 |    14.3373
 2000 |    14.2629


### slice 설명
```python
X = data[:, :-1]
y = data[:, [-1]]
```
**slice에서 ,를 기준으로 앞 부분은 행, 뒷 부분은 열을 의미한다.**<br>
" : " 을 기준으로 앞뒤로 아무것도 안 써있기 때문에 처음부터 끝까지 라는 의미<br>
y에서 [-1]은 마지막 컬럼만을 의미한다.

### W 설명
```python
W = tf.Variable(tf.random.normal((3, 1)))
```
변수가 3개 w의 low는 3개 필요. 출력 값은 y하나이므로 w의 column은 1개 필요.

### 가설 함수, 예측 함수 설명
```python
# hypothesis, prediction function
def predict(X):
    return tf.matmul(X, W) + b
```
tf.matmul => matrix multiplication
b(bias)는 이후에 생략도 가능.

# With Matrix
Matrix를 사용했을 때와 안했을 때를 비교.

### matrix를 사용하지 않을 때


$$ \begin{pmatrix} x_{ 1 } & x_{ 2 } & x_{ 3 } \end{pmatrix}\cdot \begin{pmatrix} w_{ 1 } \\ w_{ 2 } \\ w_{ 3 } \end{pmatrix} 
= x_1 w_1 + x_2 w_2 + x_3 w_3 $$


```python
# initialize w
w1 = tf.Variable(tf.random.normal([1]))
w2 = tf.Variable(tf.random.normal([1]))
w3 = tf.Variable(tf.random.normal([1]))

# hypothesis, prediction function
w1 * x1 +  w2 * x2 + w3 * x3 + b      

# update w1,w2,w3
w1.assign_sub(learning_rate * w1_grad)
w2.assign_sub(learning_rate * w2_grad)
w3.assign_sub(learning_rate * w3_grad)
```

matrix를 사용하지 않는다면 변수를 따로따로 기술해주고 이 변수의 개수만큼 w가 필요하게 된다.<br>
그렇게되면 w1 * x1 +  w2 * x2 + w3 * x3 와 같은 수식을 따로따로 써줘야하고 변수가 100개 이상이면 매우 귀찮아진다.
또한 w를 업데이트할 때도 변수의 개수만큼 assign_sub를 따로따로 기술해줘야 한다.

### matrix를 사용할 때

$$ H(X) = XW $$

```python
# initialize w
W = tf.Variable(tf.random.normal((3, 1)))

# hypothesis, prediction function
tf.matmul(X, W) + b
    
# update parameters (w and b)
W.assign_sub(learning_rate * W_grad)
```

matrix를 사용하게 되면 데이터를 기술하고 weight 정의와 연산을 한 줄로 기술이 가능하다.<br>
또한 weight를 업데이트하는 것도 weight가 matrix이므로 한 줄로 기술이 가능하다.

In [41]:
W.numpy()

array([[0.8225908 , 0.78949606]], dtype=float32)

In [42]:
b.numpy()

array([-5.3974295], dtype=float32)

In [51]:
# 우리의 모델, 우리의 예측, 우리의 가설
tf.matmul(X, W) + b

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[145.62068],
       [188.54604],
       [178.70964],
       [195.95045],
       [146.04646]], dtype=float32)>

## predict

In [52]:
Y # labels, 실제값

[152.0, 185.0, 180.0, 196.0, 142.0]

In [53]:
predict(X).numpy() # prediction, 예측값

array([[145.62068],
       [188.54604],
       [178.70964],
       [195.95045],
       [146.04646]], dtype=float32)

In [54]:
# 새로운 데이터에 대한 예측

predict([[ 89.,  95.,  92.],[ 84.,  92.,  85.]]).numpy() 

array([[179.197  ],
       [166.21233]], dtype=float32)